### ISSUE TITLE
bear gets teleported into duel area every round

### ISSUE THREAD

**Issue by dym-sh** [darklordabc/chc2issues#272]
happened in multiple games,

after the first duel bear always gets teleported into the duel area
(re-summoned into it if summoning during creep round)

**Comment by fcalife** [comment]
fixed, waiting for deploy

**Comment by Draze22** [comment]
Seems like the update didn't fix this. Not sure yet if the bug is the same as before the update or if it has changed in any way.
![image](https://user-images.githubusercontent.com/63279022/85212841-2bd5f880-b39a-11ea-9da2-55f57123e6a2.png)

**Comment by Draze22** [comment]
![image](https://user-images.githubusercontent.com/63279022/85399335-fbf54380-b599-11ea-99cd-fd4b1878dd70.png)

**Comment by Draze22** [comment]
My guess is now this bug only occurs in specific circumstances. Probably something like when the player has Aghanim's Scepter and loses a duel.

**Comment by Draze22** [comment]
This might be relevant.

![image](https://user-images.githubusercontent.com/63279022/85962082-fd879700-b9f1-11ea-9244-e96153bfefd6.png)
